### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by hmunish** [hmunish/final-capstone-backend#17]
Hi, we are 4 members of the team

@FaranoshAmini
@aradradev 
@sunga12
@hmunish 

Kanban board link:- https://github.com/hmunish/final-capstone-backend/projects/1
Front end repository link:- https://github.com/hmunish/final-capstone-frontend

![kanban](https://github.com/hmunish/final-capstone-backend/assets/121902704/df4fd7fb-f38b-4213-9175-4cf6c4edef52)

**Comment by Meltrust** [comment]
Hi @hmunish

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️


- [x] Kindly, add a description to this card:

![image](https://github.com/hmunish/final-capstone-backend/assets/57421823/8363d145-9403-4292-9870-102cbc54c9d0)

That way, we will meet that particular requirement. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- 
- All cards have descriptions now✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
